---
- name: setup my favorite settings
  include_role:
    name: YasuhiroABE.myfavorite-setting
  vars:
    mfts_hostname: "{{ hostname }}"
    mfts_sshd_listen_ipaddr: "{{ sshd_listen_address }}"

- name: setup dnsmasq
  include_role:
    name: YasuhiroABE.homegw-dnsmasq
  vars:
    dnsmasq_eth_device: "br0"
    dnsmasq_ipv4_hostprefix: "{{ internal_hostprefix }}"
    dnsmasq_ipv4_domainname: "{{ internal_domain }}"
    dnsmasq_dhcp_domain_search_list:
      - "{{ internal_domain }}."
      - "{{ external_domain }}."
    dnsmasq_dhcp_range:
      from_ipaddr: "{{ internal_dhcp_iprange_from }}"
      to_ipaddr: "{{ internal_dhcp_iprange_to }}"
    dnsmasq_ntpd_enabled: True

- name: set facts for iptables role
  set_fact:
    homegw_iptables_accept_input_eth_devices: ['lo', "{{ openvpn_tunnel_device }}"]
    homegw_iptables_accept_forward_eth_devices: [['lo','lo'],["{{ openvpn_tunnel_device }}","{{ external_eth_device }}"], ["{{ openvpn_tunnel_device }}", "br0"]]
  when: openvpn_tunnel_device|length > 0

- name: setup iptables
  include_role:
    name: YasuhiroABE.homegw-iptables
  vars:
    homegw_iptables_external_eth_device: "{{ external_eth_device }}"
    homegw_iptables_internal_eth_device: "br0"
    homegw_iptables_external_accept_tcp_ports: "{{ external_accept_tcp_ports }}"
    homegw_iptables_external_accept_udp_ports: "{{ external_accept_udp_ports }}"

- name: setup postfix
  include_role:
    name: YasuhiroABE.homegw-postfix
  vars:
    homegw_postfix_external_hostprefix: "{{ external_hostprefix }}"
    homegw_postfix_internal_hostprefix: "{{ internal_hostprefix }}"
    homegw_postfix_external_hostname: "{{ hostname }}"
    homegw_postfix_external_domainname: "{{ external_domain }}"
    homegw_postfix_internal_hostname: "{{ hostname }}"
    homegw_postfix_internal_domainname: "{{ internal_domain }}"
    homegw_postfix_relayhost: "{{ smtp_relayhost }}"

- name: setup openntpd
  include_role:
    name: YasuhiroABE.homegw-openntpd
  vars:
    homegw_openntpd_listenon_address: "{{ internal_hostprefix|ipaddr('address') }}"
    homegw_openntpd_server_addresses: "{{ external_ntp_servers }}"

- name: setup my network
  include_role:
    name: YasuhiroABE.homegw-network
  vars:
    homegw_network_setup_br0_hostprefix: "{{ internal_hostprefix }}"
    homegw_network_setup_br0_devices: "{{ internal_bridge_devices }}"
    homegw_network_setup_external_device: "{{ external_eth_device }}"
    homegw_network_setup_external_hostprefix: "{{ external_hostprefix }}"
    homegw_network_setup_external_gateway: "{{ external_gateway }}"
    homegw_network_resolv_nameservers: "{{ external_nameservers }}"
    homegw_network_resolv_search:
      - "{{ external_domain }}."
